language: objective-c
osx_image: xcode9.2

branches:
  only:
    - master

script:
    - xcodebuild clean build -sdk iphonesimulator -project WeightedRandom.xcodeproj -scheme WeightedRandom CODE_SIGNING_REQUIRED=NO
